apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rpi-uhr.fullname" . }}-breaks
  labels:
    {{- include "rpi-uhr.labels" . | nindent 4 }}
data:
  breaks.json: |-
{{ .Values.breaks.config | indent 4 }} 