version: '3.8'
services:
  production-clock:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend/breaks.json:/app/backend/breaks.json
      - ./backend/data:/app/backend/data
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=change-me
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.1'
          memory: 50M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
