# Default values for rpi-uhr
replicaCount: 1

image:
  repository: maxwalsh/rpi-uhr
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

extraEnv:
  - name: ADMIN_USERNAME
    valueFrom:
      secretKeyRef:
        name: rpi-uhr-admin
        key: ADMIN_USERNAME
  - name: ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: rpi-uhr-admin
        key: ADMIN_PASSWORD

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: rpi-uhr.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: rpi-uhr-tls
  #    hosts:
  #      - rpi-uhr.local

resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

healthCheck:
  path: /api/health
  initialDelaySeconds: 15
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

breaks:
  config: |
    {
      "breaks": [
        {"id": 1, "start": "12:00", "end": "12:30", "description": "Mittagspause"}
      ]
    }

persistence:
  enabled: true
  mountPath: /app/backend/data
  size: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClass: ""
  existingClaim: ""
  annotations: {}

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  fsGroup: 1000
